apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  image: "{{image}}"
  port: 3000
  liveness:
    path: /internal/liveness
    initialDelay: 20
  readiness:
    path: /internal/readiness
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: sdk
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 5m
      memory: 200Mi
    limits:
      memory: 2048Mi
  ingresses:
    - https://modiapersonoversikt.intern.dev.nav.no
    - https://modiapersonoversikt.ansatt.dev.nav.no
    - https://modiaflate.intern.dev.nav.no
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 200
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: false
      claims:
        groups:
          - id: "67a06857-0028-4a90-bf4c-9c9a92c7d733" # 0000-GA-BD06_ModiaGenerellTilgang
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
        - /proxy/**
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
    outbound:
      rules:
        - application: modiapersonoversikt-innstillinger
        - application: modiapersonoversikt-skrivestotte
        - application: modiapersonoversikt-draft
        - application: modiacontextholder
        - application: modiapersonoversikt-api
        - application: logging
          namespace: nais-system
      external:
        - host: personoversikt-unleash-api.nav.cloud.nais.io
  envFrom:
    - secret: modiapersonoversikt-unleash-api-token
  env:
    - name: APP_NAME
      value: "modiapersonoversikt"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: REFERRER_POLICY
      value: "no-referrer"
    - name: APP_ENVIRONMENT_NAME
      value: q2
    - name: ENVIRONMENT
      value: $(APP_ENVIRONMENT_NAME)
    - name: UNLEASH_ENVIRONMENT
      value: "development"
    - name: PUBLIC_DRAFT_WS_URL
      value: wss://modiapersonoversikt-draft.intern.dev.nav.no
    - name: PUBLIC_ENVIRONMENT
      value: $(ENVIRONMENT)
    - name: CONFIG_PATH
      value: "./proxy-config-dev.json"
    - name: LOG_LEVEL
      value: debug
