apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  image: "{{image}}"
  port: 8080
  webproxy: true
  liveness:
    path: /modiapersonoversikt/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiapersonoversikt/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /modiapersonoversikt/internal/metrics
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 600m
      memory: 1024Mi
    limits:
      cpu: 3000m
      memory: 2048Mi
  ingresses:
    - https://app.adeo.no/modiapersonoversikt
    - https://modiapersonoversikt.intern.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        groups:
          - id: "ea34edea-1e80-4759-a1d2-fbe696cf1709" # 0000-GA-BD06_ModiaGenerellTilgang
  vault:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: personoversikt-unleash-api.nav.cloud.nais.io
  envFrom:
    - secret: modiapersonoversikt-unleash-api-token
  env:
    - name: APP_NAME
      value: "modiapersonoversikt"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
    - name: CSP_DIRECTIVES
      value: "default-src 'self';\
      script-src 'self' 'unsafe-inline' jsagent.adeo.no https://cdn.adeo.no;\
      style-src 'self' 'unsafe-inline' https://cdn.nav.no;\
      img-src 'self' data:;\
      font-src 'self' data: https://cdn.nav.no;\
      connect-src 'self' eumgw.adeo.no amplitude.nav.no wss://veilederflatehendelser.adeo.no;\
      object-src blob:;\
      frame-src blob:;"
    - name: REFERRER_POLICY
      value: "no-referrer"
    - name: DATABASE_JDBC_URL
      value: "jdbc:postgresql://A01DBVL029.adeo.no:5432/modiapersonoversikt"
    - name: VAULT_MOUNTPATH
      value: "postgresql/prod-fss/"
    - name: UNLEASH_ENVIRONMENT
      value: "production"
