apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-{{q_env}}
  namespace: personoversikt
  cluster: dev-fss
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modiapersonoversikt/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiapersonoversikt/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /modiapersonoversikt/internal/metrics
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 3000m
      memory: 1536Mi
  ingresses:
    - https://app-{{ q_env }}.adeo.no/modiapersonoversikt
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: false
      claims:
        groups:
          - id: "67a06857-0028-4a90-bf4c-9c9a92c7d733" # 0000-GA-BD06_ModiaGenerellTilgang
  env:
    - name: APP_NAME
      value: "modiapersonoversikt"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: PROXY_CONFIG_FILE
      value: "/preprod-proxy-config.json"
    - name: MILJO_SUFFIX
      value: "-{{ q_env }}"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
    - name: CSP_DIRECTIVES
      value: "default-src 'self';\
      script-src 'self' 'unsafe-inline' jsagent.adeo.no https://*.hotjar.com https://*.hotjar.io;\
      style-src 'self' 'unsafe-inline';\
      img-src 'self' data: https://*.hotjar.com https://*.hotjar.io;\
      font-src 'self' data: https://*.hotjar.com https://*.hotjar.io;\
      connect-src 'self' eumgw.adeo.no wss://veilederflatehendelser-{{ q_env }}.adeo.no https://*.hotjar.com https://*.hotjar.io sentry.gc.nav.no;\
      object-src blob:;\
      frame-src blob: https://*.hotjar.com https://*.hotjar.io;\
      report-uri https://sentry.gc.nav.no/api/145/security/?sentry_key=b07212ac0fce4245b88145ad95706ce7&sentry_environment=preprod&sentry_release={{ version }};"
    - name: REFERRER_POLICY
      value: "no-referrer"
    - name: DISABLE_OPEN_AM
      value: "true"