export enum INFOTABS {
    OVERSIKT = 'OVERSIKT',
    OPPFOLGING = 'OPPFOLGING',
    MELDINGER = 'MELDINGER',
    UTBETALING = 'UTBETALING',
    SAKER = 'SAKER',
    YTELSER = 'YTELSER',
    VARSEL = 'VARSLER'
}
