const SECOND_IN_MS = 1000;
const MINUTE_IN_MS = 60 * SECOND_IN_MS;

export const RECALC_LOGIN_STATUS_INTERVAL_IN_MS = 30 * SECOND_IN_MS;
export const INACTIVITY_LIMIT_IN_MS = 10 * MINUTE_IN_MS;
export const PREEMPTIVE_REFRESH_TIME_IN_MS = 120 * SECOND_IN_MS;
export const ESTIMATED_EXPIRATION_IN_MS = 3600 * SECOND_IN_MS;
export const INVALID_EXPIRATION_DATE = -1;
