name: CI

on: [push]

env:
    CI: true
    TZ: Europe/Oslo

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.docker-build-push.outputs.image }}
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                version: 9
                run_install: false
            - uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'
                  registry-url: https://npm.pkg.github.com
            - name: Install dependencies
              run: pnpm install
              env:
                NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

            - name: Generate source files
              run: pnpm run gen:routes

            - name: Lint
              run: pnpm run lint:ci

            - name: Types
              run: pnpm run types

            - name: Test
              run: pnpm run test

            - name: Knip
              run: pnpm run knip

            - name: Build
              run: pnpm run build
              if: github.ref != 'refs/heads/master'
