name: Build & deploy to GCP

on: [push]

env:
    CI: true
    TZ: Europe/Oslo

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            id-token: write
        outputs:
            image: ${{ steps.docker-build-push.outputs.image }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Test
              run: npm run test
            - name: Build
              run: npm run build:gcp
            - name: Publish Docker image
              if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/gcp' # || github.ref = 'refs/heads/master'
              uses: nais/docker-build-push@v0
              id: docker-build-push
              with:
                dockerfile: Dockerfile.gcp
                team: personoversikt
                identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

    deploy-dev:
        name: Deploy to dev-gcp
        needs: build
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/gcp'
        runs-on: ubuntu-latest
        permissions:
          contents: read
          id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  PRINT_PAYLOAD: true
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/dev.yaml
                  VAR: version=${{ github.sha }},image=${{ needs.build.outputs.image }}
