name: Publish gh-pages

on:
    push:
        branches:
            - master
env:
    CI: true
    TZ: Europe/Oslo

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
              with:
                version: 9
                run_install: false
            - uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  registry-url: https://npm.pkg.github.com

            - name: Install dependencies
              run: pnpm install
              env:
                NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

            - name: Switch to gh-dev build
              run: |
                  echo 'VITE_USE_HASH_ROUTER=true' >> .env.development
                  mv .env.development .env.production
            - name: Build
              env:
                VITE_APP_BASE_PATH: '/modiapersonoversikt'
                VITE_GH_PAGES: 'true'
              run: pnpm run build

            - name: Deploy
              if: success()
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  build_dir: build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
