name: Publish gh-pages

on:
    push:
        branches:
            - dev
env:
    CI: true
    TZ: Europe/Oslo

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  registry-url: https://npm.pkg.github.com
            - name: Install dependencies
              run: npm ci
              env:
                NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Switch to gh-dev build
              run: |
                  echo 'VITE_USE_HASH_ROUTER=true' >> .env.development
                  mv .env.development .env.production.local
            - name: Build
              run: npm run build
            - name: Deploy
              if: success()
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  build_dir: build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
