name: "Deploy unleash api token"
on:
  push:
    paths:
      - .nais/unleash/**
      - .github/workflows/unleash.yml
jobs:
  deploy-unleash-api-token-to-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy unleash api-token to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Deploy unleash api token
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash/unleash-apitoken-preprod.yaml

  deploy-unleash-api-token-to-prod:
    if: github.ref == 'refs/heads/master'
    name: Deploy unleash api-token to prod-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Deploy unleash api token
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/unleash/unleash-apitoken-prod.yaml
